spring.application.name=senla-final-task

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/velo_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=false


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=100MB

logging.file.name=logs/app.log

logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=7
spring.output.ansi.enabled=always


app.init.admin.username=${APP_INIT_ADMIN_USERNAME:test-admin}
app.init.admin.password=${APP_INIT_ADMIN_PASSWORD:TestAdmin1!}
app.init.admin.email=${APP_INIT_ADMIN_EMAIL:test@test.com}

jwt.secret=${JWT_SECRET:default_secret_key_if_env_is_missing}
