name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn clean test
        env:
          APP_INIT_ADMIN_USERNAME: test-admin
          APP_INIT_ADMIN_PASSWORD: TestAdmin1!
          APP_INIT_ADMIN_EMAIL: test@test.com
          JWT_SECRET: jwt_secret_key_which_is_very_long_meow_meow
